#
# Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#

additional_commands:
  config_option:
    kwargs:
      DEFAULT: '*'
      DEFAULT_DISABLED: '*'
      DEPENDS: '*'
  config_string:
    flags:
    - UNQUOTE
    - UNDEF_DISABLED
    kwargs:
      DEFAULT: '*'
      DEPENDS: '*'
