# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# sel4test simulation runs
#
# See sel4test-sim/builds.yml in the repo seL4/ci-actions for configs.

name: seL4Test-Sim

on:
  push:
    branches: [master]
  pull_request:

# To reduce the load we cancel any older runs of this workflow for the current
# PR. Such runs exist, if there were new pushes to the PR's branch without
# waiting for the workflow to finish. As a side effect, pushing new commits now
# becomes a convenient way to cancel all the older runs, e.g. if they are stuck
# and would only be stopped by the timeout eventually.
# For deployment to the master branch, the workflow will run on each push, no
# skipping or cancellation will practically happen.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || format('run-{0}', github.run_id) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  simulation:
    name: Simulation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        march: [armv7a, armv8a, nehalem, rv32imac, rv64imac]
        compiler: [gcc, clang]
    steps:
    - uses: seL4/ci-actions/sel4test-sim@master
      with:
        march: ${{ matrix.march }}
        compiler: ${{ matrix.compiler }}
